
Level.create(gym_level: 1)
Level.create(gym_level: 2)
Level.create(gym_level: 3)
Level.create(gym_level: 4)
Level.create(gym_level: 5)
Level.create(gym_level: 6)
Level.create(gym_level: 7)
Level.create(gym_level: 8)
Level.create(gym_level: 9)
Level.create(gym_level: 10)
#level 1 skills
Skill.create(name: "Stretch jump onto mat and then kick to handstand and fall to flat back", type: "vault", level_id: 1)
Skill.create(name: "pullover", type: "bars", level_id: 1)
Skill.create(name: "cast", type: "bars", level_id: 1)
Skill.create(name: "back hip circle", type: "bars", level_id: 1)
Skill.create(name: "sole-circle dismount OR underswing dismount", type: "bars", level_id: 1)
Skill.create(name: "jump to front support mount", type: "beam", level_id: 1)
Skill.create(name: "cartwhell to 3/4 handstand dismount", type: "beam", level_id: 1)
Skill.create(name: "3/4 handstand", type: "floor", level_id: 1)
Skill.create(name: "cartwheel", type: "floor", level_id: 1)
Skill.create(name: "backward roll", type: "floor", level_id: 1)
Skill.create(name: "forward roll", type: "floor", level_id: 1)
Skill.create(name: "split jump with 30 degree leg separation", type: "floor", level_id: 1)
#level 2 skills
Skill.create(name: "jump to handstand on mat stack and fall to flat back", type: "vault", level_id: 2)
Skill.create(name: "pullover", type: "bars", level_id: 2)
Skill.create(name: "cast", type: "bars", level_id: 2)
Skill.create(name: "back hip circle", type: "bars", level_id: 2)
Skill.create(name: "leg cut", type: "bars", level_id: 2)
Skill.create(name: "forward stride circle", type: "bars", level_id: 2)
Skill.create(name: "single leg basket swing", type: "bars", level_id: 2)
Skill.create(name: "underswing dismount", type: "bars", level_id: 2)
Skill.create(name: "jump to front support mount", type: "beam", level_id: 2)
Skill.create(name: "arabesque to 30 degrees", type: "beam", level_id: 2)
Skill.create(name: "lever", type: "beam", level_id: 2)
Skill.create(name: "1/2 pivot turn", type: "beam", level_id: 2)
Skill.create(name: "stretch jump", type: "beam", level_id: 2)
Skill.create(name: "cartwheel to side handstand dismount", type: "beam", level_id: 2)
Skill.create(name: "handstand(held 1 second)", type: "floor", level_id: 2)
Skill.create(name: "round-off", type: "floor", level_id: 2)
Skill.create(name: "backward roll", type: "floor", level_id: 2)
Skill.create(name: "bridge back kick-over", type: "floor", level_id: 2)
Skill.create(name: "split leap with 60 degree leg separation", type: "floor", level_id: 2)
Skill.create(name: "90 degree heel snap turn", type: "floor", level_id: 2)
Skill.create(name: "split jump with 60 degree leg separation", type: "floor", level_id: 2)
#level 3 skills
Skill.create(name: "handstand flat back onto mat stack", type: "vault", level_id: 3)
Skill.create(name: "pullover", type: "bars", level_id: 3)
Skill.create(name: "front hip circle", type: "bars", level_id: 3)
Skill.create(name: "single leg squat through", type: "bars", level_id: 3)
Skill.create(name: "forward stride circle", type: "bars", level_id: 3)
Skill.create(name: "back hip circle", type: "bars", level_id: 3)
Skill.create(name: "underswing dismount", type: "bars", level_id: 3)
Skill.create(name: "handstand", type: "beam", level_id: 3)
Skill.create(name: "leap with 90 degree split", type: "beam", level_id: 3)
Skill.create(name: "straight jump", type: "beam", level_id: 3)
Skill.create(name: "side handstand dismount", type: "beam", level_id: 3)
Skill.create(name: "split jump", type: "floor", level_id:3)
Skill.create(name: "handstand forward roll", type: "floor", level_id: 3)
Skill.create(name: "handstand to a bridge kickover", type: "floor", level_id: 3)
Skill.create(name: "leap with 90 degree split", type: "floor", level_id: 3)
Skill.create(name: "backward roll to a pushup position", type: "floor", level_id: 3)
Skill.create(name: "round-off back-handspring", type: "floor", level_id: 3)
#level 4 skills
Skill.create(name: "front handspring", type: "vault", level_id: 4)
Skill.create(name: "straddle", type: "bars", level_id: 4)
Skill.create(name: "cast to horizontal", type: "bars", level_id: 4)
Skill.create(name: "squat on", type: "bars", level_id: 4)
Skill.create(name: "long hang kip", type: "bars", level_id: 4)
Skill.create(name: "back hip circle", type: "bars", level_id: 4)
Skill.create(name: "cartwheel", type: "beam", level_id: 4)
Skill.create(name: "split leap to 120 degrees", type: "beam", level_id: 4)
Skill.create(name: "cartwheel to side handstand, 1/4 turmn dismount", type: "beam", level_id: 4)
Skill.create(name: "straddle jump with 120 degree split", type: "floor", level_id: 4)
Skill.create(name: "front handspring to 2 feet", type: "floor", level_id: 4)
Skill.create(name: "back extension roll", type: "floor", level_id: 4)
Skill.create(name: "back walkover", type: "floor", level_id: 4)
Skill.create(name: "round-off back-handspring back-handspring", type: "floor", level_id: 4)
#level 5 skills
Skill.create(name: "front handspring", type: "vault", level_id: 5)
Skill.create(name: "kip", type: "bars", level_id: 5)
Skill.create(name: "cast to above horizontal", type: "bars", level_id: 5)
Skill.create(name: "clear hip to above horizontal", type: "bars", level_id: 5)
Skill.create(name: "back sole circle to clear front support", type: "bars", level_id: 5)
Skill.create(name: "backward sole circle", type: "bars", level_id: 5)
Skill.create(name: "squat on", type: "bars", level_id: 5)
Skill.create(name: "long hang kip", type: "bars", level_id: 5)
Skill.create(name: "long hang pullover", type: "bars", level_id: 5)
Skill.create(name: "tap swings", type: "bars", level_id: 5)
Skill.create(name: "flyaway dismount", type: "bars", level_id: 5)
Skill.create(name: "back walkover", type: "beam", level_id: 5)
Skill.create(name: "straight leg leap to 150 degrees", type: "beam", level_id: 5)
Skill.create(name: "split jump", type: "beam", level_id: 5)
Skill.create(name: "sissonne", type: "beam", level_id: 5)
Skill.create(name: "cartwheel to front handstand, 1/4 turn dismount", type: "beam", level_id: 5)
Skill.create(name: "straddle jump", type: "floor", level_id: 5)
Skill.create(name: "stretch jump with full turn", type: "floor", level_id: 5)
Skill.create(name: "front handspring step out, front handspring on 2 feet", type: "floor", level_id: 5)
Skill.create(name: "front tuck", type: "floor", level_id: 5)
Skill.create(name: "split leap(150 degrees)", type: "floor", level_id: 5)
Skill.create(name: "full turn", type: "floor", level_id: 5)
Skill.create(name: "roundoff back handspring back tuck", type: "floor", level_id: 5)
#level 6 skills
Skill.create(name: "front handspring", type: "vault", level_id: 6)
Skill.create(name: "1/4-1/2 twist on Tsuk entry, land on mat stack", type: "vault", level_id: 6)
Skill.create(name: "round-off entry onto table, land on mat stack", type: "vault", level_id: 6)
Skill.create(name: "cast to minimum of 45 degrees above horizontal", type: "bars", level_id: 6)
