
Level.create(gym_level: 1)
Level.create(gym_level: 2)
Level.create(gym_level: 3)
Level.create(gym_level: 4)
Level.create(gym_level: 5)
Level.create(gym_level: 6)
Level.create(gym_level: 7)
Level.create(gym_level: 8)
# Level.create(gym_level: 9)
# Level.create(gym_level: 10)
#level 1 skills
Skill.create(name: "Stretch jump onto mat and then kick to handstand and fall to flat back", category: "vault", level_id: 1)
Skill.create(name: "pullover", category: "bars", level_id: 1)
Skill.create(name: "cast", category: "bars", level_id: 1)
Skill.create(name: "back hip circle", category: "bars", level_id: 1)
Skill.create(name: "sole-circle dismount OR underswing dismount", category: "bars", level_id: 1)
Skill.create(name: "jump to front support mount", category: "beam", level_id: 1)
Skill.create(name: "cartwhell to 3/4 handstand dismount", category: "beam", level_id: 1)
Skill.create(name: "3/4 handstand", category: "floor", level_id: 1)
Skill.create(name: "cartwheel", category: "floor", level_id: 1)
Skill.create(name: "backward roll", category: "floor", level_id: 1)
Skill.create(name: "forward roll", category: "floor", level_id: 1)
Skill.create(name: "split jump with 30 degree leg separation", category: "floor", level_id: 1)
#level 2 skills
Skill.create(name: "jump to handstand on mat stack and fall to flat back", category: "vault", level_id: 2)
Skill.create(name: "pullover", category: "bars", level_id: 2)
Skill.create(name: "cast", category: "bars", level_id: 2)
Skill.create(name: "back hip circle", category: "bars", level_id: 2)
Skill.create(name: "leg cut", category: "bars", level_id: 2)
Skill.create(name: "forward stride circle", category: "bars", level_id: 2)
Skill.create(name: "single leg basket swing", category: "bars", level_id: 2)
Skill.create(name: "underswing dismount", category: "bars", level_id: 2)
Skill.create(name: "jump to front support mount", category: "beam", level_id: 2)
Skill.create(name: "arabesque to 30 degrees", category: "beam", level_id: 2)
Skill.create(name: "lever", category: "beam", level_id: 2)
Skill.create(name: "1/2 pivot turn", category: "beam", level_id: 2)
Skill.create(name: "stretch jump", category: "beam", level_id: 2)
Skill.create(name: "cartwheel to side handstand dismount", category: "beam", level_id: 2)
Skill.create(name: "handstand(held 1 second)", category: "floor", level_id: 2)
Skill.create(name: "round-off", category: "floor", level_id: 2)
Skill.create(name: "backward roll", category: "floor", level_id: 2)
Skill.create(name: "bridge back kick-over", category: "floor", level_id: 2)
Skill.create(name: "split leap with 60 degree leg separation", category: "floor", level_id: 2)
Skill.create(name: "90 degree heel snap turn", category: "floor", level_id: 2)
Skill.create(name: "split jump with 60 degree leg separation", category: "floor", level_id: 2)
#level 3 skills
Skill.create(name: "handstand flat back onto mat stack", category: "vault", level_id: 3)
Skill.create(name: "pullover", category: "bars", level_id: 3)
Skill.create(name: "front hip circle", category: "bars", level_id: 3)
Skill.create(name: "single leg squat through", category: "bars", level_id: 3)
Skill.create(name: "forward stride circle", category: "bars", level_id: 3)
Skill.create(name: "back hip circle", category: "bars", level_id: 3)
Skill.create(name: "underswing dismount", category: "bars", level_id: 3)
Skill.create(name: "handstand", category: "beam", level_id: 3)
Skill.create(name: "leap with 90 degree split", category: "beam", level_id: 3)
Skill.create(name: "straight jump", category: "beam", level_id: 3)
Skill.create(name: "side handstand dismount", category: "beam", level_id: 3)
Skill.create(name: "split jump", category: "floor", level_id:3)
Skill.create(name: "handstand forward roll", category: "floor", level_id: 3)
Skill.create(name: "handstand to a bridge kickover", category: "floor", level_id: 3)
Skill.create(name: "leap with 90 degree split", category: "floor", level_id: 3)
Skill.create(name: "backward roll to a pushup position", category: "floor", level_id: 3)
Skill.create(name: "round-off back-handspring", category: "floor", level_id: 3)
#level 4 skills
Skill.create(name: "front handspring", category: "vault", level_id: 4)
Skill.create(name: "straddle", category: "bars", level_id: 4)
Skill.create(name: "cast to horizontal", category: "bars", level_id: 4)
Skill.create(name: "squat on", category: "bars", level_id: 4)
Skill.create(name: "long hang kip", category: "bars", level_id: 4)
Skill.create(name: "back hip circle", category: "bars", level_id: 4)
Skill.create(name: "cartwheel", category: "beam", level_id: 4)
Skill.create(name: "split leap to 120 degrees", category: "beam", level_id: 4)
Skill.create(name: "cartwheel to side handstand, 1/4 turmn dismount", category: "beam", level_id: 4)
Skill.create(name: "straddle jump with 120 degree split", category: "floor", level_id: 4)
Skill.create(name: "front handspring to 2 feet", category: "floor", level_id: 4)
Skill.create(name: "back extension roll", category: "floor", level_id: 4)
Skill.create(name: "back walkover", category: "floor", level_id: 4)
Skill.create(name: "round-off back-handspring back-handspring", category: "floor", level_id: 4)
#level 5 skills
Skill.create(name: "front handspring", category: "vault", level_id: 5)
Skill.create(name: "kip", category: "bars", level_id: 5)
Skill.create(name: "cast to above horizontal", category: "bars", level_id: 5)
Skill.create(name: "clear hip to above horizontal", category: "bars", level_id: 5)
Skill.create(name: "back sole circle to clear front support", category: "bars", level_id: 5)
Skill.create(name: "backward sole circle", category: "bars", level_id: 5)
Skill.create(name: "squat on", category: "bars", level_id: 5)
Skill.create(name: "long hang kip", category: "bars", level_id: 5)
Skill.create(name: "long hang pullover", category: "bars", level_id: 5)
Skill.create(name: "tap swings", category: "bars", level_id: 5)
Skill.create(name: "flyaway dismount", category: "bars", level_id: 5)
Skill.create(name: "back walkover", category: "beam", level_id: 5)
Skill.create(name: "straight leg leap to 150 degrees", category: "beam", level_id: 5)
Skill.create(name: "split jump", category: "beam", level_id: 5)
Skill.create(name: "sissonne", category: "beam", level_id: 5)
Skill.create(name: "cartwheel to front handstand, 1/4 turn dismount", category: "beam", level_id: 5)
Skill.create(name: "straddle jump", category: "floor", level_id: 5)
Skill.create(name: "stretch jump with full turn", category: "floor", level_id: 5)
Skill.create(name: "front handspring step out, front handspring on 2 feet", category: "floor", level_id: 5)
Skill.create(name: "front tuck", category: "floor", level_id: 5)
Skill.create(name: "split leap(150 degrees)", category: "floor", level_id: 5)
Skill.create(name: "full turn", category: "floor", level_id: 5)
Skill.create(name: "roundoff back handspring back tuck", category: "floor", level_id: 5)
#level 6 skills
Skill.create(name: "front handspring", category: "vault", level_id: 6)
Skill.create(name: "1/4-1/2 twist on Tsuk entry, land on mat stack", category: "vault", level_id: 6)
Skill.create(name: "round-off entry onto table, land on mat stack", category: "vault", level_id: 6)
Skill.create(name: "cast to minimum of 45 degrees above horizontal", category: "bars", level_id: 6)
Skill.create(name: "1 bar change", category: "bars", level_id: 6)
Skill.create(name: "one 360 degree circling element that is one of the following: underswing, clear hip circle, stalder circle or hecht", category: "bars", level_id: 6)
Skill.create(name: "min A dismount", category: "bars", level_id: 6)
Skill.create(name: "either a non-flight acro series, or one acro flight element", category: "beam", level_id: 6)
Skill.create(name: "1 leap or jump requiring 180 degree split", category: "beam", level_id: 6)
Skill.create(name: "360 degree turn on one foot", category: "beam", level_id: 6)
Skill.create(name: "min of A dismount", category: "beam", level_id: 6)
Skill.create(name: "1 Acro series with at least 3 elements, 2 must have flight", category: "floor", level_id: 6)
Skill.create(name: "1 Salto or Aerial acro element", category: "floor", level_id: 6)
Skill.create(name: "Dance passage with minimum of 2 different leaps, jumps, hops - 1 must be a 180 degree split", category: "floor", level_id: 6)
Skill.create(name: "360 degree turn on one foot", category: "floor", level_id: 6)
#level 7 skills
Skill.create(name: "front handspring", category: "vault", level_id: 7)
Skill.create(name: "1/4-1/2 twist on (Tsuk entry), land on mat stack", category: "vault", level_id: 7)
Skill.create(name: "Round-off entry (Yurhenko) onto table, land on mat stack", category: "vault", level_id: 7)
Skill.create(name: "1 cast to handstand", category: "bars", level_id: 7)
Skill.create(name: "2 360 degree clear circling skills", category: "bars", level_id: 7)
Skill.create(name: "salto dismount, minimum A value", category: "bars", level_id: 7)
Skill.create(name: "an acro series with a minimum of 2 skills", category: "beam", level_id: 7)
Skill.create(name: "one acro flight skill", category: "beam", level_id: 7)
Skill.create(name: "one leap/jump requiring 180 degree split", category: "beam", level_id: 7)
Skill.create(name: "360 degree turn on one foot", category: "beam", level_id: 7)
Skill.create(name: "aerial or salto dismount that is at least A valued skill", category: "beam", level_id: 7)
Skill.create(name: "one acro series that includes a back layout", category: "floor", level_id: 7)
Skill.create(name: "a front acro series with at least 2 skill", category: "floor", level_id: 7)
Skill.create(name: "dance passage with minimum of 2 different skills, one a leap with 180n degree split", category: "floor", level_id: 7)
Skill.create(name: "360 degree turn on one foot", category: "floor", level_id: 7)
#level 8 skills
Skill.create(name: "front handspring vault", category: "vault", level_id: 8)
Skill.create(name: "minimum of bar change", category: "bars", level_id: 8)
Skill.create(name: "1 skill with flight or turn", category: "bars", level_id: 8)
Skill.create(name: "1 skill which is from one of the following groups of elements:  underswings, clear hip circles, stalder circles, circle swings or hechts", category: "bars", level_id: 8)
Skill.create(name: "a salto dismount which is a minimum of A value", category: "bars", level_id: 8)
Skill.create(name: "minimum of 1/1 360 degree turn on one foot", category: "beam", level_id: 8)
Skill.create(name: "acro series with 2 skills, one must have flight", category: "beam", level_id: 8)
Skill.create(name: "one jump/leap that reaches a 180 degree angle split", category: "beam", level_id: 8)
Skill.create(name: "aerial or salto dismount", category: "beam", level_id: 8)
Skill.create(name: "one acro series with 2 saltos or 2 directly connected saltos", category: "floor", level_id: 8)
Skill.create(name: "3 different saltos", category: "floor", level_id: 8)
Skill.create(name: "a dance passage with a minimum of two different leaps, jumps or hops, one of which is a leap with a 180 degree cross or side split — they can be directly or indirectly connected", category: "floor", level_id: 8)
Skill.create(name: "the last isolated salto or last salto connection must have at least an “A” valued salto element", category: "floor", level_id: 8)