
Level.create(gym_level: 1)
Level.create(gym_level: 2)
Level.create(gym_level: 3)
Level.create(gym_level: 4)
Level.create(gym_level: 5)
Level.create(gym_level: 6)
Level.create(gym_level: 7)
Level.create(gym_level: 8)
# Level.create(gym_level: 9)
# Level.create(gym_level: 10)
#level 1 skills
Skill.create(name: "Stretch jump onto mat and then kick to handstand and fall to flat back", type: "vault", level_id: 1)
Skill.create(name: "pullover", type: "bars", level_id: 1)
Skill.create(name: "cast", type: "bars", level_id: 1)
Skill.create(name: "back hip circle", type: "bars", level_id: 1)
Skill.create(name: "sole-circle dismount OR underswing dismount", type: "bars", level_id: 1)
Skill.create(name: "jump to front support mount", type: "beam", level_id: 1)
Skill.create(name: "cartwhell to 3/4 handstand dismount", type: "beam", level_id: 1)
Skill.create(name: "3/4 handstand", type: "floor", level_id: 1)
Skill.create(name: "cartwheel", type: "floor", level_id: 1)
Skill.create(name: "backward roll", type: "floor", level_id: 1)
Skill.create(name: "forward roll", type: "floor", level_id: 1)
Skill.create(name: "split jump with 30 degree leg separation", type: "floor", level_id: 1)
#level 2 skills
Skill.create(name: "jump to handstand on mat stack and fall to flat back", type: "vault", level_id: 2)
Skill.create(name: "pullover", type: "bars", level_id: 2)
Skill.create(name: "cast", type: "bars", level_id: 2)
Skill.create(name: "back hip circle", type: "bars", level_id: 2)
Skill.create(name: "leg cut", type: "bars", level_id: 2)
Skill.create(name: "forward stride circle", type: "bars", level_id: 2)
Skill.create(name: "single leg basket swing", type: "bars", level_id: 2)
Skill.create(name: "underswing dismount", type: "bars", level_id: 2)
Skill.create(name: "jump to front support mount", type: "beam", level_id: 2)
Skill.create(name: "arabesque to 30 degrees", type: "beam", level_id: 2)
Skill.create(name: "lever", type: "beam", level_id: 2)
Skill.create(name: "1/2 pivot turn", type: "beam", level_id: 2)
Skill.create(name: "stretch jump", type: "beam", level_id: 2)
Skill.create(name: "cartwheel to side handstand dismount", type: "beam", level_id: 2)
Skill.create(name: "handstand(held 1 second)", type: "floor", level_id: 2)
Skill.create(name: "round-off", type: "floor", level_id: 2)
Skill.create(name: "backward roll", type: "floor", level_id: 2)
Skill.create(name: "bridge back kick-over", type: "floor", level_id: 2)
Skill.create(name: "split leap with 60 degree leg separation", type: "floor", level_id: 2)
Skill.create(name: "90 degree heel snap turn", type: "floor", level_id: 2)
Skill.create(name: "split jump with 60 degree leg separation", type: "floor", level_id: 2)
#level 3 skills
Skill.create(name: "handstand flat back onto mat stack", type: "vault", level_id: 3)
Skill.create(name: "pullover", type: "bars", level_id: 3)
Skill.create(name: "front hip circle", type: "bars", level_id: 3)
Skill.create(name: "single leg squat through", type: "bars", level_id: 3)
Skill.create(name: "forward stride circle", type: "bars", level_id: 3)
Skill.create(name: "back hip circle", type: "bars", level_id: 3)
Skill.create(name: "underswing dismount", type: "bars", level_id: 3)
Skill.create(name: "handstand", type: "beam", level_id: 3)
Skill.create(name: "leap with 90 degree split", type: "beam", level_id: 3)
Skill.create(name: "straight jump", type: "beam", level_id: 3)
Skill.create(name: "side handstand dismount", type: "beam", level_id: 3)
Skill.create(name: "split jump", type: "floor", level_id:3)
Skill.create(name: "handstand forward roll", type: "floor", level_id: 3)
Skill.create(name: "handstand to a bridge kickover", type: "floor", level_id: 3)
Skill.create(name: "leap with 90 degree split", type: "floor", level_id: 3)
Skill.create(name: "backward roll to a pushup position", type: "floor", level_id: 3)
Skill.create(name: "round-off back-handspring", type: "floor", level_id: 3)
#level 4 skills
Skill.create(name: "front handspring", type: "vault", level_id: 4)
Skill.create(name: "straddle", type: "bars", level_id: 4)
Skill.create(name: "cast to horizontal", type: "bars", level_id: 4)
Skill.create(name: "squat on", type: "bars", level_id: 4)
Skill.create(name: "long hang kip", type: "bars", level_id: 4)
Skill.create(name: "back hip circle", type: "bars", level_id: 4)
Skill.create(name: "cartwheel", type: "beam", level_id: 4)
Skill.create(name: "split leap to 120 degrees", type: "beam", level_id: 4)
Skill.create(name: "cartwheel to side handstand, 1/4 turmn dismount", type: "beam", level_id: 4)
Skill.create(name: "straddle jump with 120 degree split", type: "floor", level_id: 4)
Skill.create(name: "front handspring to 2 feet", type: "floor", level_id: 4)
Skill.create(name: "back extension roll", type: "floor", level_id: 4)
Skill.create(name: "back walkover", type: "floor", level_id: 4)
Skill.create(name: "round-off back-handspring back-handspring", type: "floor", level_id: 4)
#level 5 skills
Skill.create(name: "front handspring", type: "vault", level_id: 5)
Skill.create(name: "kip", type: "bars", level_id: 5)
Skill.create(name: "cast to above horizontal", type: "bars", level_id: 5)
Skill.create(name: "clear hip to above horizontal", type: "bars", level_id: 5)
Skill.create(name: "back sole circle to clear front support", type: "bars", level_id: 5)
Skill.create(name: "backward sole circle", type: "bars", level_id: 5)
Skill.create(name: "squat on", type: "bars", level_id: 5)
Skill.create(name: "long hang kip", type: "bars", level_id: 5)
Skill.create(name: "long hang pullover", type: "bars", level_id: 5)
Skill.create(name: "tap swings", type: "bars", level_id: 5)
Skill.create(name: "flyaway dismount", type: "bars", level_id: 5)
Skill.create(name: "back walkover", type: "beam", level_id: 5)
Skill.create(name: "straight leg leap to 150 degrees", type: "beam", level_id: 5)
Skill.create(name: "split jump", type: "beam", level_id: 5)
Skill.create(name: "sissonne", type: "beam", level_id: 5)
Skill.create(name: "cartwheel to front handstand, 1/4 turn dismount", type: "beam", level_id: 5)
Skill.create(name: "straddle jump", type: "floor", level_id: 5)
Skill.create(name: "stretch jump with full turn", type: "floor", level_id: 5)
Skill.create(name: "front handspring step out, front handspring on 2 feet", type: "floor", level_id: 5)
Skill.create(name: "front tuck", type: "floor", level_id: 5)
Skill.create(name: "split leap(150 degrees)", type: "floor", level_id: 5)
Skill.create(name: "full turn", type: "floor", level_id: 5)
Skill.create(name: "roundoff back handspring back tuck", type: "floor", level_id: 5)
#level 6 skills
Skill.create(name: "front handspring", type: "vault", level_id: 6)
Skill.create(name: "1/4-1/2 twist on Tsuk entry, land on mat stack", type: "vault", level_id: 6)
Skill.create(name: "round-off entry onto table, land on mat stack", type: "vault", level_id: 6)
Skill.create(name: "cast to minimum of 45 degrees above horizontal", type: "bars", level_id: 6)
Skill.create(name: "1 bar change", type: "bars", level_id: 6)
Skill.create(name: "one 360 degree circling element that is one of the following: underswing, clear hip circle, stalder circle or hecht", type: "bars", level_id: 6)
Skill.create(name: "min A dismount", type: "bars", level_id: 6)
Skill.create(name: "either a non-flight acro series, or one acro flight element", type: "beam", level_id: 6)
Skill.create(name: "1 leap or jump requiring 180 degree split", type: "beam", level_id: 6)
Skill.create(name: "360 degree turn on one foot", type: "beam", level_id: 6)
Skill.create(name: "min of A dismount", type: "beam", level_id: 6)
Skill.create(name: "1 Acro series with at least 3 elements, 2 must have flight", type: "floor", level_id: 6)
Skill.create(name: "1 Salto or Aerial acro element", type: "floor", level_id: 6)
Skill.create(name: "Dance passage with minimum of 2 different leaps, jumps, hops - 1 must be a 180 degree split", type: "floor", level_id: 6)
Skill.create(name: "360 degree turn on one foot", type: "floor", level_id: 6)
#level 7 skills
Skill.create(name: "front handspring", type: "vault", level_id: 7)
Skill.create(name: "1/4-1/2 twist on (Tsuk entry), land on mat stack", type: "vault", level_id: 7)
Skill.create(name: "Round-off entry (Yurhenko) onto table, land on mat stack", type: "vault", level_id: 7)
Skill.create(name: "1 cast to handstand", type: "bars", level_id: 7)
Skill.create(name: "2 360 degree clear circling skills", type: "bars", level_id: 7)
Skill.create(name: "salto dismount, minimum A value", type: "bars", level_id: 7)
Skill.create(name: "an acro series with a minimum of 2 skills", type: "beam", level_id: 7)
Skill.create(name: "one acro flight skill", type: "beam", level_id: 7)
Skill.create(name: "one leap/jump requiring 180 degree split", type: "beam", level_id: 7)
Skill.create(name: "360 degree turn on one foot", type: "beam", level_id: 7)
Skill.create(name: "aerial or salto dismount that is at least A valued skill", type: "beam", level_id: 7)
Skill.create(name: "one acro series that includes a back layout", type: "floor", level_id: 7)
Skill.create(name: "a front acro series with at least 2 skill", type: "floor", level_id: 7)
Skill.create(name: "dance passage with minimum of 2 different skills, one a leap with 180n degree split", type: "floor", level_id: 7)
Skill.create(name: "360 degree turn on one foot", type: "floor", level_id: 7)
#level 8 skills
Skill.create(name: "front handspring vault", type: "vault", level_id: 8)
Skill.create(name: "minimum of bar change", type: "bars", level_id: 8)
Skill.create(name: "1 skill with flight or turn", type: "bars", level_id: 8)
Skill.create(name: "1 skill which is from one of the following groups of elements:  underswings, clear hip circles, stalder circles, circle swings or hechts", type: "bars", level_id: 8)
Skill.create(name: "a salto dismount which is a minimum of A value", type: "bars", level_id: 8)
Skill.create(name: "minimum of 1/1 360 degree turn on one foot", type: "beam", level_id: 8)
Skill.create(name: "acro series with 2 skills, one must have flight", type: "beam", level_id: 8)
Skill.create(name: "one jump/leap that reaches a 180 degree angle split", type: "beam", level_id: 8)
Skill.create(name: "aerial or salto dismount", type: "beam", level_id: 8)
Skill.create(name: "one acro series with 2 saltos or 2 directly connected saltos", type: "floor", level_id: 8)
Skill.create(name: "3 different saltos", type: "floor", level_id: 8)
Skill.create(name: "a dance passage with a minimum of two different leaps, jumps or hops, one of which is a leap with a 180 degree cross or side split — they can be directly or indirectly connected", type: "floor", level_id: 8)
Skill.create(name: "the last isolated salto or last salto connection must have at least an “A” valued salto element", type: "floor", level_id: 8)